name: Proselint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Proselint Docker image
        run: docker build . --file Dockerfile --tag proselint:v1

      - name: Run the Proselint Docker image
        run: docker run proselint:v1
